version: '3'
services:
  midserver:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    environment:
     - MID_INSTANCE_URL=${MID_INSTANCE_URL}
     - MID_INSTANCE_USERNAME=${MID_INSTANCE_USERNAME}
     - MID_INSTANCE_PASSWORD=${MID_INSTANCE_PASSWORD}
     - MID_SERVER_NAME=${MID_SERVER_NAME}