#version: '3'
services:
  mid:
    build: 
      context: mid 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      MID_INSTANCE_URL: #"https://devx.service-now.com"  
      MID_INSTANCE_USERNAME: "admin"  
      MID_INSTANCE_PASSWORD: #password 
      MID_SERVER_NAME: "vfuchs_mid"


