version: '3'
services:
  midserver:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    environment:
     - MID_INSTANCE_URL= dev256798.service-now.com
     - MID_INSTANCE_USERNAME= valenfuchs
     - MID_INSTANCE_PASSWORD= Mai123!#
     - MID_SERVER_NAME= vfuchs_mid